version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=7663200
      - MYSQL_DATABASE=gonghak98
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=7663200" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # 컨테이너 시작 후 30초 동안은 실패를 무시
    restart: always
    networks:
      - gonghak98
  was:
    container_name: was
    build:
      context: .
      dockerfile: docker/Dockerfile_Was
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gonghak98?serverTimezone=UTC&rewriteBatchedStatements=true
    depends_on:
      db:
        condition: service_healthy  # MySQL의 health check가 성공할 때까지 대기
    networks:
      - gonghak98
  nginx:
    container_name: nginx
    build: # 도커파일을 통해 이미지를 빌드할 때, 사용
      context: . # 도커 빌드 컨텍스트는 루트 경로로 지정
      dockerfile: docker/Dockerfile_Nginx
#    image: gonghak-proxy:local
    environment:
      - WAS_HOST=was
    ports:
      - 80:80
    depends_on:
      - was # was 컨테이너가 실행된 후, nginx가 실행됨
    networks:
      - gonghak98
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - gonghak98
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - gonghak98
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  grafana_data:

networks:
  gonghak98:
    driver: bridge
